from .artist import Artist
from .author import Author
from .novel import Novel
from .reading_favorite import Favorite
from .tag import Tag
from .volume import Volume
from .reading_history import ReadingHistory
from .chunk import Chunk
from .chapter import Chapter
