# Generated by Django 5.2.4 on 2025-08-16 05:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        ("novels", "0006_novel_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Bình luận",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Báo cáo",
                "verbose_name_plural": "Báo cáo",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="update_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Hoạt động"),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interactions.comment",
                verbose_name="Bình luận liên quan",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_novel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="novels.novel",
                verbose_name="Tiểu thuyết liên quan",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interactions.review",
                verbose_name="Đánh giá liên quan",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Tiêu đề",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả chi tiết"),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày xử lý"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reports_resolved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người xử lý",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Chờ xử lý"), ("RESOLVED", "Đã xử lý")],
                default="PENDING",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Hoạt động"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_reported",
            field=models.BooleanField(default=False, verbose_name="Đã báo cáo"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="like_count",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Số lượt thích",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="comments",
                to="novels.novel",
                verbose_name="Tiểu thuyết",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="replies",
                to="interactions.comment",
                verbose_name="Bình luận cha",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.TextField(verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Đã đọc"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("COMMENT", "Bình luận mới"),
                    ("REPLY", "Trả lời bình luận"),
                    ("REVIEW", "Đánh giá mới"),
                    ("LIKE", "Thích bình luận"),
                    ("REPORT", "Báo cáo"),
                    ("SYSTEM", "Hệ thống"),
                ],
                max_length=255,
                verbose_name="Loại thông báo",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reports",
                to="interactions.comment",
                verbose_name="Bình luận bị báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam"),
                    ("OFFENSIVE", "Nội dung không phù hợp"),
                    ("HARASSMENT", "Quấy rối"),
                    ("FAKE", "Thông tin giả mạo"),
                    ("COPYRIGHT", "Vi phạm bản quyền"),
                    ("OTHER", "Khác"),
                ],
                max_length=20,
                verbose_name="Lý do báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reports",
                to="interactions.review",
                verbose_name="Đánh giá bị báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reports_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người báo cáo",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="review",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviews",
                to="novels.novel",
                verbose_name="Tiểu thuyết",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                help_text="Đánh giá từ 0-5 sao",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Đánh giá",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["novel", "-created_at"], name="interaction_novel_i_382d17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "-created_at"], name="interaction_user_id_588c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="interaction_parent__447d5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="interaction_user_id_de3a0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "-created_at"], name="interaction_type_daf0a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="interaction_status_8b8d6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "-created_at"], name="interaction_user_id_2f6a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["novel", "-created_at"], name="interaction_novel_i_30398d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="interaction_user_id_d08eee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="interaction_rating_a6492a_idx"),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("comment__isnull", False),
                    ("review__isnull", False),
                    _connector="OR",
                ),
                name="report_must_have_comment_or_review",
            ),
        ),
    ]
