# Generated by Django 5.2.4 on 2025-08-19 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "interactions",
            "0002_alter_comment_options_alter_notification_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="related_comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_novel",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_review",
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Loại đối tượng",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID đối tượng"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="interaction_content_2df96f_idx",
            ),
        ),
    ]
