# Generated by Django 5.2.4 on 2025-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_remove_notification_related_comment_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="interaction_content_2df96f_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="object_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="redirect_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL chuyển hướng"
            ),
        ),
    ]
