# Generated by Django 5.2.4 on 2025-08-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL ảnh đại diện từ ImgBB",
                null=True,
                verbose_name="URL Ảnh đại diện",
            ),
        ),
    ]
