# Generated by Django 5.2.4 on 2025-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_avatar_userprofile_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                max_length=1,
                null=True,
                verbose_name="Giới tính",
            ),
        ),
    ]
