# Generated by Django 5.2.4 on 2025-07-30 16:00

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['volume', 'position']},
        ),
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='length',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='progess_status',
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 30, 15, 58, 48, 170799, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='deleted_at',
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AddField(
            model_name='novel',
            name='progress_status',
            field=models.CharField(choices=[('o', 'ONGOING'), ('c', 'COMPLETED'), ('s', 'SUSPEND')], db_index=True, default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(related_name='novels', through='novels.NovelTag', to='novels.tag'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='novel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='reading_history', to='novels.novel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='reading_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chapters', to='novels.volume'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chunks', to='novels.chapter'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorites', to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novel',
            name='approval_status',
            field=models.CharField(choices=[('d', 'DRAFT'), ('p', 'PENDING'), ('a', 'APPROVED'), ('r', 'REJECTED')], db_index=True, default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='novel',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='novels.artist'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='novels.author'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_novels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating_avg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='noveltag',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='noveltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='novels.tag'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reading_history', to='novels.chapter'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reading_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volume',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='volumes', to='novels.novel'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('volume', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('chapter', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'novel')},
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('novel', 'position')},
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='novels_arti_name_4afb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='novels_auth_name_2218d6_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['volume', 'position'], name='novels_chap_volume__8d4cde_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['approved', 'is_hidden'], name='novels_chap_approve_97d3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['chapter', 'position'], name='novels_chun_chapter_4c07fd_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='novels_favo_user_id_71b8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['novel'], name='novels_favo_novel_i_464c00_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['-created_at'], name='novels_nove_created_7408db_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['-view_count'], name='novels_nove_view_co_a5b992_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['-rating_avg'], name='novels_nove_rating__904d93_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['approval_status', '-created_at'], name='novels_nove_approva_ab9756_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['progress_status'], name='novels_nove_progres_8d17e9_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['deleted_at'], name='novels_nove_deleted_814a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='noveltag',
            index=models.Index(fields=['novel', 'tag'], name='novels_nove_novel_i_c08751_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', '-read_at'], name='novels_read_user_id_68c297_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', 'novel', '-read_at'], name='novels_read_user_id_b97e11_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['chapter'], name='novels_read_chapter_e3c476_idx'),
        ),
        migrations.AddIndex(
            model_name='volume',
            index=models.Index(fields=['novel', 'position'], name='novels_volu_novel_i_4c23f3_idx'),
        ),
    ]
