# Generated by Django 5.2.4 on 2025-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_chapter_options_alter_chunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether this novel should be displayed anonymously to public users'),
        ),
    ]
