# Generated by Django 5.2.4 on 2025-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novel_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['deleted_at'], name='novels_chap_deleted_c8620d_idx'),
        ),
    ]
