# Generated by Django 5.2.4 on 2025-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0004_chapter_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novel",
            name="tags",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("novel", "name"), ("novel", "position")},
        ),
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(
                fields=["novel", "name"], name="novels_volu_novel_i_ba7205_idx"
            ),
        ),
        migrations.DeleteModel(
            name="NovelTag",
        ),
    ]
