# Generated by Django 5.2.4 on 2025-08-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "novels",
            "0005_alter_noveltag_unique_together_remove_noveltag_novel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="tags",
            field=models.ManyToManyField(related_name="novels", to="novels.tag"),
        ),
    ]
