# Generated by Django 5.2.4 on 2025-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0006_novel_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                max_length=1,
                null=True,
            ),
        ),
    ]
